# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='部门名称')),
                ('tel', models.CharField(max_length=32, verbose_name='联系电话')),
                ('level', models.IntegerField(choices=[(1, '高级'), (2, '中级'), (3, '低级')], default=2, verbose_name='级别')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
            ],
        ),
        migrations.AddField(
            model_name='depart',
            name='proj',
            field=models.ManyToManyField(to='app01.Project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='depart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='负责人'),
        ),
    ]
